version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "staging-transaction-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k2nzgpd260u6"
s3_prefix = "staging-transaction-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

