/* Amplify Params - DO NOT EDIT
	API_SHOPAPPAPI_CUSTOMERTABLE_ARN
	API_SHOPAPPAPI_CUSTOMERTABLE_NAME
	API_SHOPAPPAPI_GRAPHQLAPIIDOUTPUT
	API_SHOPAPPAPI_KYCDOCUMENTTABLE_ARN
	API_SHOPAPPAPI_KYCDOCUMENTTABLE_NAME
	API_SHOPAPPAPI_VERIFICATIONTABLE_ARN
	API_SHOPAPPAPI_VERIFICATIONTABLE_NAME
	ENV
	REGION
Amplify Params - DO NOT EDIT */

exports.handler = async (event, context, callback) => {
	// TODO implement
	const response = {
		statusCode: 200,
		body: JSON.stringify('Hello from Lambda!'),
	};
	return response;
};
